language: rust
rust:
  - nightly

script:
  - rustup target add wasm32-unknown-unknown
  - bash ./scripts/setup.sh
  - cargo build --release
  - bash ./scripts/copy_files.sh
  - bash ./scripts/deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: "4ad3f5815248"
    - COMMIT_AUTHOR_EMAIL: "TheShallowOne@users.noreply.github.com"
