language: rust
rust:
  - nightly

script:
  - cargo install --git https://github.com/alexcrichton/wasm-gc
  - bash ./setup.sh
  - cargo build --release
  - bash ./static_files.sh
  - wasm-gc ./target/wasm32-unknown-unknown/release/synacor_vm.wasm out/synacor_vm.wasm
  - bash ./deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: "4ad3f5815248"
    - COMMIT_AUTHOR_EMAIL: "TheShallowOne@users.noreply.github.com"
